---
test:
  autosde_defaults: &autosde_defaults
    appliance_host: 9.151.190.224
    appliance_host_with_auth_token: 9.151.190.206
    site_manager_user: autosde
    site_manager_password: change_me
  autosde:
    <<: *autosde_defaults
